# Default values for nginx-helm.
namespace: incluwed
nodeSelector:
  environment: incluwed

backend:
  name: api-incluwed
  env: dev
  replicaCount: 1
  pullPolicy: Always
  image:
    repository: rvfarias/api-incluwed
    tag: "v3"
  type: ClusterIP
  port: 8000
  
postgres:
  name: postgres
  replicaCount: 1
  pullPolicy: IfNotPresent
  image:
    repository: postgres
    tag: "13"
  port: 5432
  type: ClusterIP
  secret:
    type: Opaque
    envs:
      POSTGRES_HOST: cG9zdGdyZXMuaW5jbHV3ZWQK
      POSTGRES_DB: cG9zdGdyZXM=
      POSTGRES_USER: cG9zdGdyZXM=
      POSTGRES_PASSWORD: YXBp

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
    
