apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  labels:
    app: {{ .Values.backend.name}}
    version: {{ .Values.backend.image.tag }}
    env: {{ .Values.backend.env }}

spec:
  type: {{ .Values.backend.type }}
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
      name: http
  
  selector:
      app: {{ .Values.backend.name}}
      env: {{ .Values.backend.env }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
spec:
  selector:
    app: {{ .Values.postgres.name }}
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
      protocol: TCP
  type: {{ .Values.postgres.type }}
